import Pokemon from './pokemon';

export const Pokedex: Array<Pokemon> = [
	{
		id: 1,
		name: 'Bulbasaur',
		hp: 45,
		attack: 49,
		defense: 49,
		specialAttack: 65,
		specialDefense: 65,
		speed: 45,
		types: ['Grass', 'Poison'],
		moves: ['Solar Beam', 'Razor Leaf', 'Vine Whip', 'Tackle'],
		picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/001.png',
		created: new Date()
	},
	{
		id: 2,
		name: 'Ivysaur',
		hp: 60,
		attack: 62,
		defense: 63,
		specialAttack: 80,
		specialDefense: 80,
		speed: 60,
		types: ['Grass', 'Poison'],
		moves: ['Solar Beam', 'Razor Leaf', 'Vine Whip', 'Tackle'],
		picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/002.png',
		created: new Date()
	},
	{
		id: 3,
		name: 'Venusaur',
		hp: 80,
		attack: 82,
		defense: 83,
		specialAttack: 100,
		specialDefense: 100,
		speed: 80,
		types: ['Grass', 'Poison'],
		moves: ['Solar Beam', 'Razor Leaf', 'Vine Whip', 'Tackle'],
		picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/003.png',
		created: new Date()
	},
	{
		id: 4,
		name: 'Charmander',
		hp: 39,
		attack: 52,
		defense: 43,
		specialAttack: 60,
		specialDefense: 50,
		speed: 65,
		types: ['Fire'],
		moves: ['Flamethrower', 'Fire Blast', 'Wing Attack', 'Fly'],
		picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/004.png',
		created: new Date()
	},
	{
		id: 5,
		name: 'Charmeleon',
		hp: 58,
		attack: 64,
		defense: 58,
		specialAttack: 80,
		specialDefense: 65,
		speed: 80,
		types: ['Fire'],
		moves: ['Flamethrower', 'Fire Blast', 'Wing Attack', 'Fly'],
		picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/005.png',
		created: new Date()
	},
	{
		id: 6,
		name: 'Charizard',
		hp: 78,
		attack: 84,
		defense: 78,
		specialAttack: 109,
		specialDefense: 85,
		speed: 100,
		types: ['Fire', 'Flying'],
		moves: ['Flamethrower', 'Fire Blast', 'Wing Attack', 'Fly'],
		picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/006.png',
		created: new Date()
	},
	{
		id: 7,
		name: 'Squirtle',
		hp: 44,
		attack: 48,
		defense: 65,
		specialAttack: 50,
		specialDefense: 64,
		speed: 43,
		types: ['Water'],
		moves: ['Hydro Pump', 'Water Gun', 'Bubble Beam', 'Surf'],
		picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/007.png',
		created: new Date()
	},
	{
		id: 8,
		name: 'Wartortle',
		hp: 59,
		attack: 63,
		defense: 80,
		specialAttack: 65,
		specialDefense: 80,
		speed: 58,
		types: ['Water'],
		moves: ['Hydro Pump', 'Water Gun', 'Bubble Beam', 'Surf'],
		picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/008.png',
		created: new Date()
	},
	{
		id: 9,
		name: 'Blastoise',
		hp: 79,
		attack: 83,
		defense: 100,
		specialAttack: 85,
		specialDefense: 105,
		speed: 78,
		types: ['Water'],
		moves: ['Hydro Pump', 'Water Gun', 'Bubble Beam', 'Surf'],
		picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/009.png',
		created: new Date()
	},
	{
		id: 25,
		name: 'Pikachu',
		hp: 35,
		attack: 55,
		defense: 40,
		specialAttack: 50,
		specialDefense: 50,
		speed: 90,
		types: ['Electric'],
		moves: ['Thunder Shock', 'Thunderbolt', 'Thunder', 'Quick Attack'],
		picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/025.png',
		created: new Date()
	}
];

export default Pokedex;